#!/usr/bin/env bash

export JAVA_HOME="$HOME/.sdkman/candidates/java/current/"
export M2_HOME="$HOME/.sdkman/candidates/maven/current"
export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
export ANDROID_HOME="$ANDROID_SDK_ROOT"

export PATH="$PATH:$JAVA_HOME/bin:$M2_HOME/bin"
export PATH="$PATH:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools"